<nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="header">
		<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    <table>
    	<tr>
		<td width="500px;"><a class="nav-link" href="index.php?c=product&a=grid">PRODUCT</a></td>
		<td width="500px;"><a class="nav-link" href="index.php?c=category&a=grid">CATEGORY</a></td>
		<td width="500px;"><a class="nav-link" href="index.php?c=customer&a=grid">CUSTOMER</a></td>
		<td width="500px;"><a class="nav-link" href="index.php?c=vendor&a=grid">VENDOR</a></td>
		<td width="500px;"><a class="nav-link" href="index.php?c=salesman&a=grid">SALESMAN</a></td>
	</tr>
		</table>
		</button>
</div>
</nav>