<?php
$product = $this->getData('product');
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table width="100%" align="center">
		<form method="POST" action="<?php echo $this->getUrl('save');?>">
			<table align="center">
				<tr align="center">
					<td><h2>EDIT PRODUCTS</h2></td>
				</tr>
				<tr align="center">
					<td><input type="submit" value="SAVE"> 
						<button><a href="index.php?c=product&a=grid">CANCEL</a></button></td>
				</tr>
			</table>
			<table border="2" align="center" cellpadding="10px">
				<tr>
					<td>Name</td>
					<td><input type="text" name="product[name]" value="<?php echo $product->name;?>">
					</td>
				</tr>
				<tr>
					<td>sku</td>
					<td><input type="text" name="product[sku]" value="<?php echo $product->sku;?>">
						<input type="hidden" name="id" value="<?php  echo $id ?>">
					</td>
				</tr>
				<tr>
					<td>Price</td>
					<td><input type="text" name="product[price]" value="<?php echo $product->price;?>">
					</td>
				</tr>
				<tr>
					<td>Quantity</td>
					<td><input type="text" name="product[quantity]" value="<?php echo $product->quantity;?>">
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td><input type="text" name="product[description]" value="<?php echo $product->description;?>">
					</td>
				</tr>
				<?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
			    <tr>
			      <td>Status</td>
			      <td>
			         <select name="product[status]">
			         <?php foreach ($statusOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($product->status==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
			   <?php $colorOptions = [1=>"Red" , 2=>"yellow", 3=>"blue", 4=>"brown"];?>
			    <tr>
			      <td>Color</td>
			      <td>
			         <select name="product[color]">
			         <?php foreach ($colorOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($product->color==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
				<tr>
					<td>Material</td>
					<td><input type="text" name="product[material]" value="<?php echo $product->material;?>">
					</td>
				</tr>
			</table>
		</form>
	</table>
</body>
</html>