<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Product</title>
</head>
<body>

<table border="0" width="100%" cellpadding="20">
	<tr>
	<td width="100%">
		<h1 align="center">Modify product</h1>
	</td>
</tr>
<tr align="center">
	<td >
		<a href="index.php?c=product&a=add">ADD NEW product</a>
	</td>
	</tr>
</table>
<table border="1" width="100%" cellpadding="15"  >
	<tr  >
		<th>Product_id</th>
		<th>Name</th>
		<th>Sku</th>
		<th>Cost</th>
		<th>Status</th>
		<th>Created_at</th>
		<th>Updated_at</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
 	</tr>
 	<?php  foreach ($products as $key => $method): ?>
 	<tr>
 		<td><?php echo $method['product_id']; ?></td>
 		<td><?php echo $method['name']; ?></td>
 		<td><?php echo $method['sku']; ?></td>
 		<td><?php echo $method['cost']; ?></td>
 		<td><?php echo $method['status']; ?></td>
 		<td><?php echo $method['created_at']; ?></td>
 		<td><?php echo $method['updated_at']; ?></td>
 		<td><a href="index.php?c=product&a=edit&id=<?php echo $method['product_id'];?>">EDIT</a></td>
 		<td><a href="index.php?c=product&a=delete&id=<?php echo $method['product_id'];?>">DELETE</a></td>
 	</tr>
 	<?php endforeach; ?>

</table>
</body>
</html>