<?php
require_once 'View/html/header.phtml';
$products = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Product</title>
</head>
<body>

<table  width="100%" cellpadding="20">
	<tr>
	<td width="100%">
		<h1 align="center">Modify product</h1>
	</td>
</tr>
</table>
<table border="1" align="center">
<tr >
	<td  >
		<a href="index.php?c=product&a=add">ADD NEW product</a>
	</td>
	</tr>
</table>
<table border="1" width="100%" cellpadding="15"  >
	<tr  >
		<th>Product_id</th>
		<th>Name</th>
		<th>Sku</th>
		<th>Price</th>
		<th>Quatity</th>
		<th>Description</th>
		<th>Status</th>
		<th>Color</th>
		<th>Material</th>
		<th>Created_at</th>
		<th>Updated_at</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
 	</tr>
 	<?php  foreach ($products as $product): ?>
 	<tr>
 		<td><?php echo $product->product_id; ?></td>
 		<td><?php echo $product->name; ?></td>
 		<td><?php echo $product->sku; ?></td>
 		<td><?php echo $product->price; ?></td>
 		<td><?php echo $product->quantity; ?></td>
 		<td><?php echo $product->description; ?></td>
 		<td><?php echo $product->status; ?></td>
 		<td><?php echo $product->color; ?></td>
 		<td><?php echo $product->material; ?></td>
 		<td><?php echo $product->created_at; ?></td>
 		<td><?php echo $product->updated_at; ?></td>
 		<td><a href="index.php?c=product&a=edit&id=<?php echo $product->product_id;?>">EDIT</a></td>
 		<td><a href="index.php?c=product&a=delete&id=<?php echo $product->product_id;?>">DELETE</a></td>
 	</tr>
 	<?php endforeach; ?>

</table>
</body>
</html>