<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table border="2" cellspacing="10px" width="100%">
		<tr height="100" align="center">
			<td colspan="3"><?php $this->getChild('header')->render();?></td>
		</tr>
		
		<tr height="260" align="center">
			<td width="90%"><?php $this->getChild('content')->render();?></td>
		</tr>
		<tr height="50" align="center">
			<td colspan="3"><?php $this->getChild('footer')->render();?></td>
		</tr>
	</table>
</body>
</html>