<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
    <table width="100%" align="center">
        <form method="POST" action="index.php?c=customer&a=save">
            <table align="center">
                <tr align="center">
                    <td><h2>ADD CUSTOMERS</h2></td>
                </tr>
                <tr align="center">
                    <td><input type="submit" value="SAVE"> 
                        <button><a href="index.php?c=customer&a=grid">CANCEL</a></button></td>
                </tr>
            </table>
            <table border="2" align="center" cellpadding="10px">
                 <tr>
                    <td>Firstname</td>
                    <td><input type="text" name="customer[firstname]"></td>
                </tr>
                <tr>
                    <td>lastname</td>
                    <td><input type="text" name="customer[lastname]"></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="text" name="customer[email]"></td>
                </tr>
	           <?php $genderOptions = [1=>"Male" , 2=>"female"];?>
	           <tr>
	              <td>gender</td>
	              <td>
	                 <select name="customer[gender]">
	                        <?php foreach ($genderOptions as $value => $label):?>
	                        <option value="<?php echo $value;?>"><?php echo $label;?></option>
	                        <?php endforeach; ?>
	                    </select>
	              </td>
	           </tr>
                 <tr>
                    <td>Mobile</td>
                    <td><input type="text" name="customer[mobile]"></td>
                </tr>
                <?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
           <tr>
              <td>Status</td>
              <td>
                 <select name="customer[status]">
                        <?php foreach ($statusOptions as $value => $label):?>
                        <option value="<?php echo $value;?>"><?php echo $label;?></option>
                        <?php endforeach; ?>
                    </select>
              </td>
           </tr> 
       </table>
       <table align="center">
           <tr align="center">
                    <td><h2>ADD Address</h2></td>
                </tr>
            </table>
             <table border="2" align="center" cellpadding="10px">
                 <tr>
                    <td>Address</td>
                    <td><input type="text" name="customer_address[address]"></td>
                </tr>
                <tr>
                    <td>City</td>
                    <td><input type="text" name="customer_address[city]"></td>
                </tr>
                <tr>
                    <td>state</td>
                    <td><input type="text" name="customer_address[state]"></td>
                </tr>
                 <tr>
                    <td>Country</td>
                    <td><input type="text" name="customer[country]"></td>
                </tr>
                <tr>
                    <td>Zipcode</td>
                    <td><input type="text" name="customer[zipcode]"></td>
                </tr> 
       </table>
        </form>
    </table>
</body>
</html>