<?php
$customer = $this->getData('customer');
$customerAddress = $this->getData('customerAddress');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
    <table width="100%" align="center">
        <form method="POST" action="<?php echo $this->getUrl('save');?>">
            <table align="center">
                <tr align="center">
                    <td><h2>ADD CUSTOMERS</h2></td>
                </tr>
                <tr align="center">
                    <td><input type="submit" value="SAVE"> 
                        <button><a href="index.php?c=customer&a=grid">CANCEL</a></button></td>
                </tr>
            </table>
            <table border="2" align="center" cellpadding="10px">
                 <tr>
                    <td>Firstname</td>
                    <td><input type="text" name="customer[firstname]" value="<?php echo $customer->first_name;?>"></td>
                </tr>
                <tr>
                    <td>lastname</td>
                    <td><input type="text" name="customer[lastname]" value="<?php echo $customer->last_name;?>"></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="text" name="customer[email]" value="<?php echo $customer->email;?>"></td>
                </tr>
	             <?php $genderOptions = [1=>"male" , 2=>"female"];?>
			    <tr>
			      <td>gender</td>
			      <td>
			         <select name="customer[gender]">
			         <?php foreach ($genderOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($customer->gender==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
                 <tr>
                    <td>Mobile</td>
                    <td><input type="text" name="customer[mobile]" value="<?php echo $customer->email;?>"></td>
                </tr>
               <?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
			    <tr>
			      <td>Status</td>
			      <td>
			         <select name="customer[status]">
			         <?php foreach ($statusOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($customer->status==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
       </table>
       <table align="center">
           <tr align="center">
                    <td><h2>ADD Address</h2></td>
                </tr>
            </table>
             <table border="2" align="center" cellpadding="10px">
                 <tr>
                    <td>Address</td>
                    <td><input type="text" name="customer_address[address]" value="<?php echo $customerAddress->address;?>"></td>
                </tr>
                <tr>
                    <td>City</td>
                    <td><input type="text" name="customer_address[city]" value="<?php echo $customerAddress->city;?>"></td>
                </tr>
                <tr>
                    <td>state</td>
                    <td><input type="text" name="customer_address[state]" value="<?php echo $customerAddress->state;?>"></td>
                </tr>
                 <tr>
                    <td>Country</td>
                    <td><input type="text" name="customer_address[country]" value="<?php echo $customerAddress->country;?>"></td>
                </tr>
                <tr>
                    <td>Zipcode</td>
                    <td><input type="text" name="customer_address[zipcode]" value="<?php echo $customerAddress->zipcode;?>"></td>
                </tr> 
       </table>
        </form>
    </table>
</body>
</html>