<?php
require_once 'View/html/header.phtml';
$customers = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> CUSTOMER</title>
</head>
<body>

<table  width="100%" cellpadding="20">
	<tr>
	<td width="100%">
		<h1 align="center">Modify Customer</h1>
	</td>
</tr>
</table>
<table border="1" align="center">
<tr >
	<td  >
		<a href="index.php?c=customer&a=add">ADD NEW Customer</a>
	</td>
	</tr>
</table>
<table border="1" width="100%" cellpadding="15"  >
	<tr  >
		<th>Customer_id</th>
		<th>Firstname</th>
		<th>Lastname</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Mobile</th>
		<th>Status</th>
		<th>Created_at</th>
		<th>Updated_at</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
 	</tr>
 	<?php  foreach ($customers as $customer): ?>
 	<tr>
 		<td><?php echo $customer->customer_id; ?></td>
 		<td><?php echo $customer->firstname; ?></td>
 		<td><?php echo $customer->lastname; ?></td>
 		<td><?php echo $customer->email; ?></td>
 		<td><?php echo $customer->gender; ?></td>
 		<td><?php echo $customer->mobile; ?></td>
 		<td><?php echo $customer->status; ?></td>
 		<td><?php echo $customer->created_at; ?></td>
 		<td><?php echo $customer->updated_at; ?></td>
 		<td><a href="index.php?c=customer&a=edit&id=<?php echo $customer->customer_id;?>">EDIT</a></td>
 		<td><a href="index.php?c=customer&a=delete&id=<?php echo $customer->customer_id;?>">DELETE</a></td>
 	</tr>
 	<?php endforeach; ?>

</table>
</body>
</html>