<?php
$category = $this->getData('category');

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<table width="100%" align="center">
		<form method="POST" action="<?php echo $this->getUrl('save');?>">
			<table align="center">
				<tr align="center">
					<td><h2>EDIT CATEGORY</h2></td>
				</tr>
				<tr align="center">
					<td><input type="submit" value="SAVE"> 
						<button><a href="index.php?c=category&a=grid">CANCEL</a></button></td>
				</tr>
			</table>
			<table border="2" align="center" cellpadding="10px">
				<tr>
					<td>Name</td>
					<td><input type="text" name="category[name]" value="<?php echo $category->name;?>">
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td><input type="text" name="category[description]" value="<?php echo $category->description;?>">
					</td>
				</tr>
				<?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
			    <tr>
			      <td>Status</td>
			      <td>
			         <select name="category[status]">
			         <?php foreach ($statusOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($category->status==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
			</table>
		</form>
	</table>
</body>
</html>