<?php
$salesman = $this->getData('salesman');
$salesmanAddress = $this->getData('salesmanAddress');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
    <table width="100%" align="center">
        <form method="POST" action="index.php?c=salesman&a=save&id=<?php echo $salesman->salesman_id?>">
            <table align="center">
                <tr align="center">
                    <td><h2>ADD salesmanS</h2></td>
                </tr>
                <tr align="center">
                    <td><input type="submit" value="SAVE"> 
                        <button><a href="index.php?c=salesman&a=grid">CANCEL</a></button></td>
                </tr>
            </table>
            <table border="2" align="center" cellpadding="10px">
                 <tr>
                    <td>Firstname</td>
                    <td><input type="text" name="salesman[firstname]" value="<?php echo $salesman->firstname;?>"></td>
                        <input type="hidden" name="id" value="<?php  echo $id ?>">
                </tr>
                <tr>
                    <td>lastname</td>
                    <td><input type="text" name="salesman[lastname]" value="<?php echo $salesman->lastname;?>"></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="text" name="salesman[email]" value="<?php echo $salesman->email;?>"></td>
                </tr>
	             <?php $genderOptions = [1=>"male" , 2=>"female"];?>
			    <tr>
			      <td>gender</td>
			      <td>
			         <select name="salesman[gender]">
			         <?php foreach ($genderOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($salesman->gender==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
                 <tr>
                    <td>Mobile</td>
                    <td><input type="text" name="salesman[mobile]" value="<?php echo $salesman->email;?>"></td>
                </tr>
               <?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
			    <tr>
			      <td>Status</td>
			      <td>
			         <select name="salesman[status]">
			         <?php foreach ($statusOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($salesman->status==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
       </table>
       <table align="center">
           <tr align="center">
                    <td><h2>ADD Address</h2></td>
                </tr>
            </table>
             <table border="2" align="center" cellpadding="10px">
                 <tr>
                    <td>Address</td>
                    <td><input type="text" name="salesman_address[address]" value="<?php echo $salesmanAddress->address;?>"></td>
                </tr>
                <tr>
                    <td>City</td>
                    <td><input type="text" name="salesman_address[city]" value="<?php echo $salesmanAddress->city;?>"></td>
                </tr>
                <tr>
                    <td>state</td>
                    <td><input type="text" name="salesman_address[state]" value="<?php echo $salesmanAddress->state;?>"></td>
                </tr>
                 <tr>
                    <td>Country</td>
                    <td><input type="text" name="salesman_address[country]" value="<?php echo $salesmanAddress->country;?>"></td>
                </tr>
                <tr>
                    <td>Zipcode</td>
                    <td><input type="text" name="salesman_address[zipcode]" value="<?php echo $salesmanAddress->zipcode;?>"></td>
                </tr> 
       </table>
        </form>
    </table>
</body>
</html>