<?php
require_once 'View/html/header.phtml';
$salesmans = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> SALESMAN</title>
</head>
<body>

<table  width="100%" cellpadding="20">
	<tr>
	<td width="100%">
		<h1 align="center">Modify Salesman</h1>
	</td>
</tr>
</table>
<table border="1" align="center">
<tr >
	<td  >
		<a href="index.php?c=salesman&a=add">ADD NEW SALESMAN</a>
	</td>
	</tr>
</table>
<table border="1" width="100%" cellpadding="15"  >
	<tr  >
		<th>salesman_id</th>
		<th>Firstname</th>
		<th>Lastname</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Mobile</th>
		<th>Status</th>
		<th>Company</th>
		<th>Created_at</th>
		<th>Updated_at</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
 	</tr>
 	<?php  foreach ($salesmans as $salesman): ?>
 	<tr>
 		<td><?php echo $salesman->salesman_id; ?></td>
 		<td><?php echo $salesman->firstname; ?></td>
 		<td><?php echo $salesman->lastname; ?></td>
 		<td><?php echo $salesman->email; ?></td>
 		<td><?php echo $salesman->gender; ?></td>
 		<td><?php echo $salesman->mobile; ?></td>
 		<td><?php echo $salesman->status; ?></td>
 		<td><?php echo $salesman->company; ?></td>
 		<td><?php echo $salesman->created_at; ?></td>
 		<td><?php echo $salesman->updated_at; ?></td>
 		<td><a href="index.php?c=salesman&a=edit&id=<?php echo $salesman->salesman_id;?>">EDIT</a></td>
 		<td><a href="index.php?c=salesman&a=delete&id=<?php echo $salesman->salesman_id;?>">DELETE</a></td>
 	</tr>
 	<?php endforeach; ?>

</table>
</body>
</html>